[versions]
androidGradlePlugin = "9.0.1"
kotlin = "2.3.20"
androidxCore = "1.15.0"
androidxAppcompat = "1.7.0"
material = "1.12.0"
androidxActivity = "1.10.1"
androidxSwiperefreshlayout = "1.1.0"
androidxWebkit = "1.12.1"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidxAppcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
androidx-activity = { module = "androidx.activity:activity-ktx", version.ref = "androidxActivity" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "androidxSwiperefreshlayout" }
androidx-webkit = { module = "androidx.webkit:webkit", version.ref = "androidxWebkit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
